apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    //    // 远程Maven引入联运SDK
    implementation 'com.hihonor.mcs:game:2.0.21.301'
    // banner广告依赖库
    implementation 'com.hihonor.mcs.lite:ads-banner:16.0.5.300'
    // 激励视频依赖库
    implementation 'com.hihonor.mcs.lite:ads-reward:16.0.5.300'
    // 插屏广告依赖库
    implementation 'com.hihonor.mcs.lite:ads-interstitial:16.0.5.300'
    implementation "com.tencent:mmkv:1.2.13"
    implementation 'com.google.code.gson:gson:2.8.9' // 补单解析可能需要 Json 库
    
**DEPS**}

android {
    namespace "com.unity3d.player"
    ndkPath "**NDKPATH**"
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
