pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':unityLibrary'
include ':Plugin',':SampleMiGameSdk'
include ':jar-anti'
include ':jar-base'
include ':jar-client'
include ':onetrack'
include ':achievement'
include ':milink'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven {
               url 'https://maven.xiaomi.com/repository/public/'
        }
        maven { url 'https://maven.aliyun.com/repository/public' }   // 阿里云公共仓库
        maven { url 'https://maven.aliyun.com/repository/google' }   // 阿里云 Google 镜像
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }      
        google()
        mavenCentral()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
        maven { url "https://jitpack.io" }       
    }
}
